server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



spring:
  mvc:
    servlet:
      load-on-startup: 10
  application:
    #应用的名称，可选
    name: 供应链管理系统
  banner:
    location: banner.txt
  # SQL数据库连接
  datasource:
    # 连接池阿里的
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scms
      username: root
      password: 123456




  servlet:
    multipart:
      # 文件上传的最大值
      max-file-size: 10MB
      # 文件请求的最大值
      max-request-size: 10MB
      # 临时文件存储路径
      location: D:/red1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # sql查询日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



